# Generated by Django 3.0.1 on 2019-12-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='weight',
            field=models.FloatField(),
        ),
    ]
